### ISSUE TITLE
copycopter:deploy times out

### ISSUE THREAD

**Issue by aaronjensen** [copycopter/copycopter-ruby-client#10]
``` text
$rake copycopter:deploy
rake aborted!
Timeout::Error: Timeout::Error

Tasks: TOP => copycopter:deploy
(See full trace by running task with --trace)
```

We have a fairly large project. I have no way of knowing if the deploy actually finishes eventually or not. Either way, it probably needs to be faster and/or have the timeout extended.

Stack trace:

``` text
/Users/aaronjensen/.rvm/gems/ruby-1.9.2-p290/gems/copycopter_client-1.1.1/lib/copycopter_client/client.rb:112:in `rescue in connect'
/Users/aaronjensen/.rvm/gems/ruby-1.9.2-p290/gems/copycopter_client-1.1.1/lib/copycopter_client/client.rb:109:in `connect'
/Users/aaronjensen/.rvm/gems/ruby-1.9.2-p290/gems/copycopter_client-1.1.1/lib/copycopter_client/client.rb:74:in `deploy'
/Users/aaronjensen/.rvm/gems/ruby-1.9.2-p290/gems/copycopter_client-1.1.1/lib/copycopter_client.rb:24:in `deploy'
/Users/aaronjensen/.rvm/gems/ruby-1.9.2-p290/gems/copycopter_client-1.1.1/lib/tasks/copycopter_client_tasks.rake:4:in `block (2 levels) in <top (required)>'
```

**Comment by jasonm** [comment]
Hi Aaron,

It's a known issue that the deploy process (on the copycopter.com server side) can take too long.  Although I can't specifically say when it'll be improved, this is an issue we'd like to address.  Thanks for opening an issue - we'll update this ticket with information as we improve the deploy speed.

Thanks,
-Jason

**Comment by aaronjensen** [comment]
In the meantime, is it possible to know if it's actually working or not? Or is the timeout interrupting the server too?

**Comment by jasonm** [comment]
Hey Aaron,

I think this is an issue because deploys are just taking a while on the server, and the client is currently unwilling to wait. Can you try increasing the timeout in your client configuration to see if the deploy will go through?

```
CopycopterClient.configure do |config|
  config.http_read_timeout = 30
  config.http_open_timeout = 30
end
```

Thanks,
Jason

**Comment by aaronjensen** [comment]
30 seconds wasn't enough. Raising it further (120 seconds) gave me this error: 

```
503: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
    <html>
    <head>
      <meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title></head>
    </head>
    <body>
      <iframe src="https://s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>

```

**Comment by jasonm** [comment]
Hi Aaron,

I've opened a support ticket at http://help.copycopter.com/ and invited you to it for this issue.  It looks like the deploy is not successfully going through, but that's a service issue rather than an issue with the client gem.

Thanks,
-Jason

**Comment by jasonm** [comment]
Closing since this isn't a client gem issue, the discussion is moving to a private support thread.
