### ISSUE TITLE
Timeout::Error: execution expired 

### ISSUE THREAD

**Issue by dblock** [copycopter/copycopter-ruby-client#14]
I deleted my `tmp` and am now getting Timeout::Error: execution expired.

```
** [Copycopter] [P:79066] [T:70241002134060] Timeout::Error: execution expired
** [Copycopter] [P:79066] [T:70241002133200] Timeout::Error: execution expired
** [Copycopter] [P:79066] [T:70241002133200] Timeout::Error: execution expired
```

It blocks my HTTP requests, at least in development environment. I would expect it to fallback to the default and timeout "quickly", no? Does it work the same in production, ie. when copycopter is having a problem I get a site that's down?

Rails 3.1.3, asset pipeline disabled.

**Comment by jferris** [comment]
In production, copycopter_client uses a background thread to periodically synchronize with the server, so performance problems on our server will not affect your application in production.

In development, the client tries to synchronize before each request to eliminate long feedback loops while adding copy. We currently don't have any code to detect server issues, so this means the client is slow in development when our server is slow to respond.

We realize this downtime isn't acceptable; I'm sorry for the trouble and we're working to improve our performance.

P.S.: in the future, we'd appreciate it if you could file support requests here: http://help.copycopter.com/

**Comment by dblock** [comment]
Thanks. Will do.
