### ISSUE TITLE
Rails 3.1.beta1 i18n conflict

### ISSUE THREAD

**Issue by sfsekaran** [copycopter/copycopter-ruby-client#5]
We wanted to test migrating to rails 3.1, but  Rails 3.1 depends on i18n 0.6.0beta1, which conflicts with copycopter_client's i18n ~> 0.5.0 dependency.

**Comment by hgmnz** [comment]
Thanks, this has now been addressed by depending on I18n >= 0.5.0

**Comment by sfsekaran** [comment]
Thanks!
