### ISSUE TITLE
rake copycopter:deploy raises Timeout::Error

### ISSUE THREAD

**Issue by logankoester** [copycopter/copycopter-ruby-client#8]
Running `rake copycopter:deploy` in my Rails 3.1 application using copycopter_client 1.1.1 fails with Timeout::Error: Timeout::Error. I do not see any other way to see which blurbs have changes in draft state or to publish them. We have experienced this from different machines on different networks throughout the day.

Trace:
    *\* Invoke copycopter:deploy (first_time)  
    *\* Invoke environment (first_time)  
    *\* Invoke env_loaded_from_rake (first_time)  
    *\* Execute env_loaded_from_rake  
    *\* Execute environment  
    *\* Execute copycopter:deploy  
    rake aborted!  
    Timeout::Error: Timeout::Error  
    ruby-1.9.3-preview1@my_application_application/gems/copycopter_client-1.1.1/lib/copycopter_client/client.rb:112:in `rescue in connect'                                                                                                            
    ruby-1.9.3-preview1@my_application_application/gems/copycopter_client-1.1.1/lib/copycopter_client/client.rb:109:in`connect'  
    ruby-1.9.3-preview1@my_application_application/gems/copycopter_client-1.1.1/lib/copycopter_client/client.rb:74:in `deploy'                                                                                                                        
    ruby-1.9.3-preview1@my_application_application/gems/copycopter_client-1.1.1/lib/copycopter_client.rb:24:in`deploy'  
    ruby-1.9.3-preview1@my_application_application/gems/copycopter_client-1.1.1/lib/tasks/copycopter_client_tasks.rake:4:in `block (2 levels) in <top (required)>'                                                                                    
    ruby-1.9.3-preview1@global/gems/rake-0.9.2/lib/rake/task.rb:205:in`call'  
    ruby-1.9.3-preview1@global/gems/rake-0.9.2/lib/rake/task.rb:205:in `block in execute'                      
    ruby-1.9.3-preview1@global/gems/rake-0.9.2/lib/rake/task.rb:200:in`each'  
    ruby-1.9.3-preview1@global/gems/rake-0.9.2/lib/rake/task.rb:200:in `execute'                               
    ruby-1.9.3-preview1@global/gems/rake-0.9.2/lib/rake/task.rb:158:in`block in invoke_with_call_chain'  
    ruby-1.9.3-preview1/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'                                   
    ruby-1.9.3-preview1@global/gems/rake-0.9.2/lib/rake/task.rb:151:in`invoke_with_call_chain'  
    ruby-1.9.3-preview1@global/gems/rake-0.9.2/lib/rake/task.rb:144:in `invoke'                                
    ruby-1.9.3-preview1@global/gems/rake-0.9.2/lib/rake/application.rb:112:in`invoke_task'  
    ruby-1.9.3-preview1@global/gems/rake-0.9.2/lib/rake/application.rb:90:in `block (2 levels) in top_level'   
    ruby-1.9.3-preview1@global/gems/rake-0.9.2/lib/rake/application.rb:90:in`each'  
    ruby-1.9.3-preview1@global/gems/rake-0.9.2/lib/rake/application.rb:90:in `block in top_level'              
    ruby-1.9.3-preview1@global/gems/rake-0.9.2/lib/rake/application.rb:129:in`standard_exception_handling'  
    ruby-1.9.3-preview1@global/gems/rake-0.9.2/lib/rake/application.rb:84:in `top_level'                       
    ruby-1.9.3-preview1@global/gems/rake-0.9.2/lib/rake/application.rb:62:in`block in run'  
    ruby-1.9.3-preview1@global/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'    
    ruby-1.9.3-preview1@global/gems/rake-0.9.2/lib/rake/application.rb:59:in`run'  
    ruby-1.9.3-preview1@global/gems/rake-0.9.2/bin/rake:32:in `<top (required)>'                               
    ruby-1.9.3-preview1@my_application_application/bin/rake:19:in`load'  
    ruby-1.9.3-preview1@my_application_application/bin/rake:19:in `<main>'  
    Tasks: TOP => copycopter:deploy

**Comment by jferris** [comment]
Hey there,

Can you please open a support ticket here? http://help.copycopter.com/

Please include your account name, and I'll take a look into why you're getting these timeouts.

Thanks,
-Joe

**Comment by logankoester** [comment]
I followed your instructions 2 days ago and have still received no reply.

http://help.copycopter.com/discussions/problems/28-rake-copycopterdeploy-raises-timeouterror
